### ISSUE TITLE
multiple databases at startup

### ISSUE THREAD

**Issue by maslick** [orchardup/docker-postgresql#20]
Is it possible to create multiple databases at startup?

**docker-compose.yml**

```
db:
    image: postgres
    environment:
        - POSTGRES_DB=db1
        - POSTGRES_DB=db2
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=pwd
        - POSTGRES_ROOT_PASSWORD=rootpwd
```
